name = "secretchecker-api"
main = "src/index.js"
compatibility_date = "2025-08-30"

# Serve API at separate subdomain
routes = [
  { pattern = "secretchecker-api.ciancode.com/*", zone_name = "ciancode.com" },
]
